baseURL = 'https://dariuszh.uk/'
languageCode = 'en-us'
title = "Dariusz Huk"
theme = 'ananke'

[params]
author = "Dariusz Huk"
text_color = ""
favicon = "favicon.ico"
site_logo = ""
description = "Personal website of Dariusz Huk, software engineer"
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-gray"
custom_css = ["custom.css"]

[[params.ananke_socials]]
name = "github"
url = "https://github.com/dariusz-hq"
color = '#FFFFFF'
[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/dariuszhuk/"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Skills"
url = "/skills/"
weight = 2
[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3
[[menu.main]]
name = "Experience"
url = "/experience/"
weight = 4
[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 5